// db.js
const bancoDeDados = {
    // ANIMES
    "Ore": "ore",
    "ore": "ore",
    "ore dake": "ore",
    "one room": "one",
    "danny": "danny",
    "Danny": "danny",
    "danny phantom": "danny",
    "Danny phantom": "danny",
    "the franxx": "darling",
    "darling"  : "darling",
    "darling in the franxx"  : "darling",
    "death"  : "death",
    "Death"  : "death",
    "death march"  : "death",
    "dungeon ni deai"  : "ni_deai",
    "ni deai"  : "ni_deai",
    "dungeon"  : "ni_deai",
    "Bleach"  : "bleach",
    "bleach"  : "bleach",
    "BLEACH"  : "bleach",
    "death note"  : "death_note",
    "Death Note"  : "death_note",
    "dandandan"  : "dandandan",
    "Dandandan"  : "dandandan",
    "DanDanDan"  : "dandandan",
};
